# This workflow will automerge PRs created by dependabot

name: Dependabot Automerge

on:
  workflow_run:
    workflows: ['Node.js CI']
    types: [completed]

jobs:
  worker:
    runs-on: ubuntu-latest

    if: "github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]'"
    steps:
      - name: automerge
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_requests[0].number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_requests[0].number
            })
