# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Format
      run: yarn format
    - name: Check Types
      run: yarn types:check
    - name: Run Build
      run: yarn build
    - name: Run Tests
      run: yarn test
    - name: Create package
      run: yarn pack
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: "*.tgz"

